# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(600, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_connect = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_connect.sizePolicy().hasHeightForWidth())
        self.btn_connect.setSizePolicy(sizePolicy)
        self.btn_connect.setObjectName("btn_connect")
        self.horizontalLayout.addWidget(self.btn_connect)
        self.lab_status = QtWidgets.QLabel(self.centralwidget)
        self.lab_status.setObjectName("lab_status")
        self.horizontalLayout.addWidget(self.lab_status)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.combo_periph = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_periph.sizePolicy().hasHeightForWidth())
        self.combo_periph.setSizePolicy(sizePolicy)
        self.combo_periph.setObjectName("combo_periph")
        self.verticalLayout.addWidget(self.combo_periph)
        self.tree_regs = QtWidgets.QTreeWidget(self.centralwidget)
        self.tree_regs.setObjectName("tree_regs")
        self.verticalLayout.addWidget(self.tree_regs)
        self.lab_info = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_info.sizePolicy().hasHeightForWidth())
        self.lab_info.setSizePolicy(sizePolicy)
        self.lab_info.setMinimumSize(QtCore.QSize(0, 56))
        self.lab_info.setFrameShape(QtWidgets.QFrame.Box)
        self.lab_info.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lab_info.setText("")
        self.lab_info.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lab_info.setObjectName("lab_info")
        self.verticalLayout.addWidget(self.lab_info)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.act_quit = QtWidgets.QAction(MainWindow)
        self.act_quit.setObjectName("act_quit")
        self.act_autoread = QtWidgets.QAction(MainWindow)
        self.act_autoread.setCheckable(True)
        self.act_autoread.setChecked(False)
        self.act_autoread.setObjectName("act_autoread")
        self.act_autowrite = QtWidgets.QAction(MainWindow)
        self.act_autowrite.setCheckable(True)
        self.act_autowrite.setChecked(False)
        self.act_autowrite.setObjectName("act_autowrite")
        self.act_open_svd = QtWidgets.QAction(MainWindow)
        self.act_open_svd.setObjectName("act_open_svd")
        self.act_about = QtWidgets.QAction(MainWindow)
        self.act_about.setObjectName("act_about")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.act_open_svd)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.act_quit)
        self.menuSettings.addAction(self.act_autoread)
        self.menuSettings.addAction(self.act_autowrite)
        self.menuHelp.addAction(self.act_about)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.act_quit.triggered.connect(MainWindow.close)
        self.btn_connect.clicked.connect(MainWindow.btn_connect_clicked)
        self.act_open_svd.triggered.connect(MainWindow.act_open_svd_triggered)
        self.act_autoread.triggered['bool'].connect(MainWindow.act_autoread_triggered)
        self.act_autowrite.triggered['bool'].connect(MainWindow.act_autowrite_triggered)
        self.combo_periph.currentIndexChanged['int'].connect(MainWindow.combo_periph_changed)
        self.act_about.triggered.connect(MainWindow.act_about_triggered)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "openocd-svd"))
        self.btn_connect.setText(_translate("MainWindow", "Connect"))
        self.lab_status.setText(_translate("MainWindow", "Not connected to OpenOCD"))
        self.tree_regs.headerItem().setText(0, _translate("MainWindow", "Property"))
        self.tree_regs.headerItem().setText(1, _translate("MainWindow", "Value"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.act_quit.setText(_translate("MainWindow", "Quit"))
        self.act_quit.setStatusTip(_translate("MainWindow", "Quit the utility"))
        self.act_quit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.act_autoread.setText(_translate("MainWindow", "Auto read"))
        self.act_autoread.setStatusTip(_translate("MainWindow", "Control registers automatic reading"))
        self.act_autowrite.setText(_translate("MainWindow", "Auto write"))
        self.act_autowrite.setStatusTip(_translate("MainWindow", "Control registers automatic writing"))
        self.act_open_svd.setText(_translate("MainWindow", "Open SVD file"))
        self.act_open_svd.setStatusTip(_translate("MainWindow", "Open SVD file"))
        self.act_open_svd.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.act_about.setText(_translate("MainWindow", "About"))
        self.act_about.setStatusTip(_translate("MainWindow", "Show information about utility"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

